### ISSUE TITLE
Connection unrecoverables after RabbitMQ server restart

### ISSUE THREAD

**Issue by kavat** [logstash-plugins/logstash-output-rabbitmq#55]
Hi,
we restarted our rabbitmq server for a maintenance and logstash clients started to write in the log file this string:

[2016-12-30T13:42:32,108][ERROR][logstash.outputs.rabbitmq] Error while publishing. Will retry. {:message=>"#method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)", :exception=>MarchHare::ChannelAlreadyClosed, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/channel.rb:980:in `converting_rjc_exceptions_to_ruby'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/channel.rb:978:in `converting_rjc_exceptions_to_ruby'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/channel.rb:606:in `basic_publish'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/exchange.rb:77:in `publish'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-4.0.4-java/lib/logstash/outputs/rabbitmq.rb:54:in `publish'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-3.0.2/lib/logstash/codecs/json.rb:42:in `encode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-4.0.4-java/lib/logstash/outputs/rabbitmq.rb:47:in `receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:42:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:297:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:296:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:252:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:225:in `start_workers'"]}

The solution was restart the logstash service.

We use:
- Ubuntu 14.04
- Logstash 5.1.1 (package from apt)
- logstash-output-rabbitmq 4.0.4

The logstash configuration is set with the heartbeat parameter, like bottom:

        rabbitmq {
            exchange => "logstash"
            exchange_type => "topic"
            host => "XXX.XXX.XXX.XXX"
            port => "XXXX"
            user => "user"
            password => "password"
            key => ""
            ssl => true
            heartbeat => "5"
        }

Can you help us please?

**Comment by kavat** [comment]
Another thing that I observed was the name of directory of march_hare.
I understood about this that it is the client used from logstash-output-rabbitmq to connect to rabbitmq.
On the servers with logstash that they are not able to reconnect the plugin seems has name march_hare-2.20.0-java, on a server windows 2012 R2 that was able to reconnect was called march_hare-2.15.0-java.
I don't know if this can help you.

**Comment by kavat** [comment]
Hi,
can anyone help us please?

**Comment by andrewvc** [comment]
@kavat it looks like you shutdown your rabbitmq cluster with rabbitmqctl. Is that correct? Did the error message ever go away?

**Comment by kavat** [comment]
Hi @andrewvc ,
I restarted my RabbitMQ with reboot command.
I continued see the error until I restarted logstash service.
Why has not logstash client retried the connection and it has entered into this error log infinite loop?

**Comment by kavat** [comment]
Hi @andrewvc,
In the next days we have to restart out rabbitmq server and we are worried about this.
Have my informations helped you in your analysis? Have you got any news?
Sorry but we need a urgent fix or workaround.

**Comment by kavat** [comment]
Any news?

**Comment by andrewvc** [comment]
@kavat AFAIK `rabbitmqctl` has no `reboot` command, you can stop and start it. I assume you're using an init script?

At any rate, I just tested it with a manual start and a `rabbitmqctl stop` and everything worked great.

The logstash config I used was: `bin/logstash -e "input { stdin {} } output { rabbitmq { exchange => foobar exchange_type => fanout host => localhost} }"`

I'll need a detailed reproducible test case to go any further with this.

It might even make sense to upload a virtualbox VM demonstrating this error.

Given that others haven't reported this error I *am* leaning toward this being an environment issue. RabbitMQ is very finicky to setup and there is a large amount of variation between environments.

**Comment by kavat** [comment]
I've reboot the entire linux server rabbitmq, with the command via ssh reboot.
The server went down and the client started to write in log 

[2016-12-30T13:42:32,108][ERROR][logstash.outputs.rabbitmq] Error while publishing. Will retry. {:message=>"#method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)", :exception=>MarchHare::ChannelAlreadyClosed, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/exceptions.rb:121:in convert_and_reraise'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/channel.rb:980:inconverting_rjc_exceptions_to_ruby'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/channel.rb:978:in converting_rjc_exceptions_to_ruby'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/channel.rb:606:inbasic_publish'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.20.0-java/lib/march_hare/exchange.rb:77:in publish'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-4.0.4-java/lib/logstash/outputs/rabbitmq.rb:54:inpublish'", "org/jruby/RubyProc.java:281:in call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-3.0.2/lib/logstash/codecs/json.rb:42:inencode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-4.0.4-java/lib/logstash/outputs/rabbitmq.rb:47:in receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:inmulti_receive'", "org/jruby/RubyArray.java:1613:in each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:inmulti_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:42:inmulti_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:297:in output_batch'", "org/jruby/RubyHash.java:1342:ineach'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:296:in output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:252:inworker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:225:in `start_workers'"]}

Also when the server recover itself the log continue to append the string before.

Is it clear now?

**Comment by andrewvc** [comment]
@kavat I already tried rebooting the server, didn't get the same error. What you've submitted is not a sufficient test case.

If you can create a VM image that demonstrates this effect I'd be glad to take a look.

**Comment by Ghaithjemai** [comment]
I'am having the same error logstash can't recover rabbitmq connection after restarting rabbitmq-server 


RabbitMQ connection was closed! {XXXX} :automatic_recovery=>true, :cause=>com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)}

**Comment by ara-mark** [comment]
Today i've encountered the same issue, is there any workaround?

**Comment by magnusbaeck** [comment]
This is still a problem with Logstash 9.3.1. In our case we had a transient LDAP auth problem on the RabbitMQ side, resulting in a message publish operation being rejected. Here's the result (newlines added for readability):
```
[2026-03-01T10:31:58,066][ERROR][logstash.outputs.rabbitmq] Error while publishing, will retry
{:backtrace=>["/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/march_hare-4.8.0-java/lib/march_hare/exceptions.rb:127:in `convert_and_reraise'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/march_hare-4.8.0-java/lib/march_hare/channel.rb:1123:in `converting_rjc_exceptions_to_ruby'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/march_hare-4.8.0-java/lib/march_hare/channel.rb:736:in `basic_publish'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/march_hare-4.8.0-java/lib/march_hare/exchange.rb:77:in `publish'", 
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-integration-rabbitmq-7.4.1-java/lib/logstash/outputs/rabbitmq.rb:77:in `block in publish'", 
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/back_pressure-1.0.0/lib/back_pressure/gated_executor.rb:133:in `execute'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-integration-rabbitmq-7.4.1-java/lib/logstash/outputs/rabbitmq.rb:76:in `publish'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-integration-rabbitmq-7.4.1-java/lib/logstash/outputs/rabbitmq.rb:68:in `block in multi_receive_encoded'",
"org/jruby/RubyArray.java:2009:in `each'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-integration-rabbitmq-7.4.1-java/lib/logstash/outputs/rabbitmq.rb:67:in `multi_receive_encoded'",
"/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:102:in `multi_receive'", 
"org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in `multi_receive'",
"/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:315:in `block in start_workers'"], 
:exception=>MarchHare::ChannelAlreadyClosed,
:message=>"#method<channel.close>(reply-code=403, reply-text=ACCESS_REFUSED - write access to topic 'REDACTED' in exchange 'REDACTED' in vhost '/' refused for user 'REDACTED', backend rabbit_auth_backend_ldap returned an error: ldap_connect_error, class-id=60, method-id=40)",
:cause=>#<Java::ComRabbitmqClient::AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=403, reply-text=ACCESS_REFUSED - write access to topic 'REDACTED' in exchange 'REDACTED' in vhost '/' refused for user 'REDACTED', backend rabbit_auth_backend_ldap returned an error: ldap_connect_error, class-id=60, method-id=40)>}
```
This wouldn't recover on its own for a couple of hours and I eventually restarted Logstash. I didn't try a configuration reload. I can reproduce this from the RabbitMQ management interface by forcibly closing the connection. Here's an example of that:
```
[2026-03-02T07:09:05,261][ERROR][logstash.outputs.rabbitmq] Error while publishing, will retry
{:backtrace=>["/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/march_hare-4.8.0-java/lib/march_hare/exceptions.rb:127:in `convert_and_reraise'", 
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/march_hare-4.8.0-java/lib/march_hare/channel.rb:1123:in `converting_rjc_exceptions_to_ruby'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/march_hare-4.8.0-java/lib/march_hare/channel.rb:736:in `basic_publish'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/march_hare-4.8.0-java/lib/march_hare/exchange.rb:77:in `publish'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-integration-rabbitmq-7.4.1-java/lib/logstash/outputs/rabbitmq.rb:77:in `block in publish'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/back_pressure-1.0.0/lib/back_pressure/gated_executor.rb:133:in `execute'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-integration-rabbitmq-7.4.1-java/lib/logstash/outputs/rabbitmq.rb:76:in `publish'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-integration-rabbitmq-7.4.1-java/lib/logstash/outputs/rabbitmq.rb:68:in `block in multi_receive_encoded'",
"org/jruby/RubyArray.java:2009:in `each'",
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-integration-rabbitmq-7.4.1-java/lib/logstash/outputs/rabbitmq.rb:67:in `multi_receive_encoded'",
"/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:102:in `multi_receive'",
"org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in `multi_receive'",
"/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:315:in `block in start_workers'"], 
:exception=>MarchHare::ChannelAlreadyClosed,
:message=>"#method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - Closing to test recovery behavior, class-id=0, method-id=0)",
:cause=>#<Java::ComRabbitmqClient::AlreadyClosedException: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - Closing to test recovery behavior, class-id=0, method-id=0)>}
```

**Comment by magnusbaeck** [comment]
Please disregard my previous comment. It was a misconfiguration on our end. (There could still be other circumstances where automatic recovery doesn't work.)

**Comment by jsvd** [comment]
Hey @magnusbaeck long time no see :) Did you have to change something on the Logstash side to have recovery?
I've been looking at this and there is definitely a recover issue in the output: whenever the channel closes -MarchHare::ChannelAlreadyClosed - but the connection is still valid, the automated recovery doesn't kick in.

In:

```ruby
      rescue MarchHare::Exception, IOError, AlreadyClosedException, TimeoutException => e
        @logger.error("Error while publishing, will retry", error_details(e, backtrace: true))

        sleep_for_retry
        retry
      end
```

Should probably be:

```ruby
      rescue MarchHare::Exception, IOError, MarchHare::ChannelAlreadyClosed, TimeoutException => e
        @logger.error("Error while publishing, will retry", error_details(e, backtrace: true))

        # this reset allows `local_exchange` and `local_channel` to create new instances on the next call
        if e.is_a?(MarchHare::ChannelAlreadyClosed)
          @thread_local_exchange.remove
          @thread_local_channel.remove
        end
        sleep_for_retry
        retry
      end
```

**Comment by magnusbaeck** [comment]
It turned out one of our many rabbitmq outputs had explicitly disabled automatic recovery. Finding `:automatic_recovery=>false` in the log made me reexamine the configuration. We had automatic recovery temporarily disabled while testing a new way to provision credentials since we didn't want it to retry incorrect credentials and cause a lockout situation before we had time to react.

The patch you suggest seems to make sense. From my experience, it's not obvious when you can recover from a channel problem by just opening a new channel. I usually just tear everything down if there's an error.

I wasn't able to create a minimal example that reproduces the problem, at least not when closing the connection from the server like in the second log snippet I posted above. Your code example indicates that closing just the channel could result in a different outcome.

**Comment by magnusbaeck** [comment]
Incidentally, a [current thread on the rabbitmq-users mailing list](https://groups.google.com/g/rabbitmq-users/c/o3CYAtpsBj8/m/OsqSJbRHAQAJ) discussed this very matter (how to distinguish between channel and connection closures).
