### ISSUE TITLE
why "Unknown setting 'queue' for rabbitmq"

### ISSUE THREAD

**Issue by jack161641** [logstash-plugins/logstash-output-rabbitmq#86]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version:5.1.1
- Operating System:centos 7.2
- Config File (if you have sensitive info, please remove it):
    rabbitmq {
      host => "10.129.65.222:60796"
      exchange => "logsX"
      exchange_type => "topic"
      user => "admin"
      password => "admin"
      vhost => "logsVH"
      queue => "logsQ"
    }

- Sample Data:
[2019-05-10T20:01:09,719][ERROR][logstash.outputs.rabbitmq] Unknown setting 'queue' for rabbitmq
[2019-05-10T20:01:09,720][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Something is wrong with your configuration.", :backtrace=>["/app/logstash-6.6.1/logstash-core/lib/logstash/config/mixin.rb:86:in `config_init'", "/app/logstash-6.6.1/logstash-core/lib/logstash/outputs/base.rb:60:in `initialize'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:224:in `initialize'", "org/logstash/config/ir/compiler/OutputDelegatorExt.java:48:in `initialize'", "org/logstash/config/ir/compiler/OutputDelegatorExt.java:30:in `initialize'", "org/logstash/plugins/PluginFactoryExt.java:235:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:181:in `plugin'", "/app/logstash-6.6.1/logstash-core/lib/logstash/pipeline.rb:71:in `plugin'", "(eval):194:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/app/logstash-6.6.1/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "/app/logstash-6.6.1/logstash-core/lib/logstash/pipeline_action/reload.rb:43:in `block in execute'", "/app/logstash-6.6.1/logstash-core/lib/logstash/agent.rb:94:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/app/logstash-6.6.1/logstash-core/lib/logstash/agent.rb:94:in `exclusive'", "/app/logstash-6.6.1/logstash-core/lib/logstash/pipeline_action/reload.rb:39:in `execute'", "/app/logstash-6.6.1/logstash-core/lib/logstash/agent.rb:327:in `block in converge_state'"]}

- Steps to Reproduce:

**Comment by yaauie** [comment]
In RabbitMQ, messages are published to an _exchange_, not to a specific _queue_.

Because there is no way for a publisher to publish messages to a specific queue, that is not an option that the RabbitMQ Output Plugin presents; supplying a value here doesn't make sense.

> The core idea in the messaging model in RabbitMQ is that the producer never sends any messages directly to a queue. Actually, quite often the producer doesn't even know if a message will be delivered to any queue at all.
> 
> Instead, the producer can only send messages to an _exchange_. An exchange is a very simple thing. On one side it receives messages from producers and the other side it pushes them to queues. The exchange must know exactly what to do with a message it receives. [...]
> -- [RabbitMQ Docs](https://www.rabbitmq.com/tutorials/tutorial-three-java.html)
