### ISSUE TITLE
march_hare 4.0.0 and 4.1.0 bug crashes plugin 

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-output-rabbitmq#89]
In the latest march_hare versions 4.0.0 and 4.1.9 a bug was introduced in https://github.com/ruby-amqp/march_hare/blob/v4.0.0/lib/march_hare/session.rb#L91 (`opts` is undefined) which crashes the plugins like this

```
[2019-09-06T17:49:09,625][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"shipper", :exception=>#<NameError: undefined local variable or method `opts' for MarchHare::Session:Class>, :backtrace=>["org/jruby/RubyBasicObject.java:1708:in `method_missing'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.0-java/lib/march_hare/session.rb:91:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.0-java/lib/march_hare.rb:24:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-mixin-rabbitmq_connection-5.1.0-java/lib/logstash/plugin_mixins/rabbitmq_connection.rb:201:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-mixin-rabbitmq_connection-5.1.0-java/lib/logstash/plugin_mixins/rabbitmq_connection.rb:138:in `connect!'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-rabbitmq-5.1.1-java/lib/logstash/outputs/rabbitmq.rb:47:in `register'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:106:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:48:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:259:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:270:in `block in register_plugins'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:270:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:611:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:280:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:217:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:176:in `block in start'"], :thread=>"#<Thread:0x66f57e21 run>"}
```

Relevant bit is 
```
#<NameError: undefined local variable or method `opts' for MarchHare::Session:Class>, :backtrace=>["org/jruby/RubyBasicObject.java:1708:in `method_missing'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/march_hare-4.1.0-java/lib/march_hare/session.rb:91:in `connect'", 
```

**Comment by colinsurprenant** [comment]
submitted PR upstream https://github.com/ruby-amqp/march_hare/pull/145

**Comment by michaelklishin** [comment]
March Hare `4.1.1`  includes the  above PR. Thank you for contributing!

**Comment by colinsurprenant** [comment]
Thanks @michaelklishin for your help with this. 

To pick up the new `march_hare` version 4.1.1, a simple plugin update should do the trick. For example, with versions verifications, from logstash home:
```
$ grep -e logstash-mixin-rabbitmq_connection -e march_hare Gemfile.lock
      logstash-mixin-rabbitmq_connection (>= 5.0.0, < 6.0.0)
    logstash-mixin-rabbitmq_connection (5.0.2-java)
      march_hare (~> 3.0)
      logstash-mixin-rabbitmq_connection (>= 5.0.0, < 6.0.0)
    march_hare (3.1.1-java)

$ bin/logstash-plugin update logstash-input-rabbitmq logstash-output-rabbitmq
Updating logstash-input-rabbitmq, logstash-output-rabbitmq
No plugin updated

$ grep -e logstash-mixin-rabbitmq_connection -e march_hare Gemfile.lock
      logstash-mixin-rabbitmq_connection (>= 5.0.0, < 6.0.0)
    logstash-mixin-rabbitmq_connection (5.1.0-java)
      march_hare (~> 4.0)
      logstash-mixin-rabbitmq_connection (>= 5.0.0, < 6.0.0)
    march_hare (4.1.1-java)
``````

Closing.
